- small_eod/cases/templates/admin/cases/case/change_list.html
- small_eod/cases/templates/admin/cases/letter/change_list.html
> Updatte column weight in change list

- .github/workflows/python.yaml
- docker-compose.yml
> trigger github workflow on docker-compose changes

- backend-project/small_eod/collections/tests/test_views.py
- backend-project/small_eod/institutions/factories.py
- backend-project/small_eod/institutions/tests/test_views.py
Poprawiłem fabrykę Institutions tak, żeby nowe testy działały prawidłowo. Pracowałem na ostatnim działającym commicie. Właściwie nie wiem, czy powinienem w tym momencie zgłaszać Pull request czy poczekać aż wszystko zacznie działać.
> Iss119 factories

- backend-project/contrib/github/script.sh
Wygląda na to, że startują dwa procesy migracji jednocześnie, co prowadzi do wyścigu.
> Fix race in migration - close #258

- frontend-project/src/pages/cases/new/index.jsx
- frontend-project/src/pages/institutions/new/index.tsx
> new institution/case non-unique id fix

- backend-project/Dockerfile
Cześć.
Przydało by się przypiąć conajmniej wersje minor, aby łamiące zmiany nie popsuły projektu. A co ważniejsze, abym wiedział jaką wersje zainstalować w wirtualnym środowisku.
Wybrałem Python 3.7, ponieważ jest to najpopularniejsza aktualnie wersja Python. Aktualnie nie mam jeszcze Python 3.8 zainstalowanego na komputerze.
[https://pypistats.org/packages/__all__](https://pypistats.org/packages/__all__)
Pozdrawiam
> Pin Python version

- frontend-project/src/pages/Admin.tsx
- frontend-project/src/pages/Authorized.tsx
- frontend-project/src/pages/Welcome.tsx
#322 
Zostaje tylko katalog user do przeniesienia, jak się reszta PR zamknie
Było dużo chińskich znaczków do przetłumaczenia na na angielski, a google tłumacz nie dawał rady, to się starałem na czuja
> Przeniesienie 'luźnych' stron do typescriptu

- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
> usunięcie kolumny name z listy listów

- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
in/out zamienione na odebrane/wysłane w liście listów
> in/out zamienione na odebrane/wysłane w liście listów 

- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
Dodanie kolumny Instytucja do listy listów
> Dodanie kolumny Instytucja do listy listów 

- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
Dodanie kolumn utworzono zmodyfikowano w liście listów
> Dodanie kolumn utworzono zmodyfikowano w liście listów

- frontend-project/src/components/Table/CaseName.tsx
- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
- frontend-project/src/services/cases.ts
Dodanie kolumny sprawy do listy listów,
nowy komponent CaseName
funkcja pobierająca pojedynczą sprawę
> Dodanie kolumny sprawy do listy listów

- frontend-project/src/pages/cases/list/index.tsx
- frontend-project/src/services/cases.ts
Przegapiłem na code review to naprawiam
@mateuszmagulski jakbyś widział gdzieś jeszcze `[typ]` zamiast `typ[]` albo `Array<typ>` to pisz
Fixes #433
> Naprawienie typów w liście spraw

- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
Dodanie kolumny z liczbą załączników do listy listów
> Dodanie kolumny z liczbą załączników do listy listów

- backend-project/requirements/development.txt
- backend-project/small_eod/institutions/tests/test_views.py
- backend-project/small_eod/institutions/views.py
Fix: https://github.com/watchdogpolska/small_eod/issues/337
> Add filter by name to InstitutionViewSet

- frontend-project/src/pages/letters/list/index.tsx
- frontend-project/src/pages/letters/list/locales/en-US.ts
- frontend-project/src/pages/letters/list/locales/pl-PL.ts
> zmiana institutions na institution w liście listów

- frontend-project/src/pages/letters/list/index.tsx
migracja listy listów do komponentu ogólnego Table
> migracja do komponentu ogólnego Table - lista listów

- backend-project/small_eod/cases/factories.py
- backend-project/small_eod/cases/serializers.py
- backend-project/small_eod/cases/tests/test_factories.py
- backend-project/small_eod/cases/tests/test_views.py
- backend-project/small_eod/collections/tests/test_views.py
- backend-project/small_eod/generic/factories.py
- backend-project/small_eod/letters/tests/test_views.py
@fivelamps, rozbudowałem obsługę zagnieżdżonych serializatorów. Mam nadzieje, że to pomoże w #356 .
> Add support for implicit m2m-subfactory

- frontend-project/config/config.ts
- frontend-project/src/locales/en-US/menu.ts
- frontend-project/src/locales/pl-PL/menu.ts
- frontend-project/src/pages/users/list/index.tsx
- frontend-project/src/pages/users/list/locales/en-US.ts
- frontend-project/src/pages/users/list/locales/pl-PL.ts
- frontend-project/src/services/users.ts
> Lista użytkowników

- backend-project/small_eod/cases/urls.py
- backend-project/small_eod/collections/tests/test_views.py
- backend-project/small_eod/collections/urls.py
- backend-project/small_eod/files/tests/test_views.py
- backend-project/small_eod/letters/tests/test_views.py
- backend-project/small_eod/letters/urls.py
Reported by @magul . Break API compatibility.
> Unify plurals endpoints URL

- backend-project/small_eod/institutions/factories.py
- backend-project/small_eod/institutions/serializers.py
- backend-project/small_eod/institutions/tests/test_serializers.py
- backend-project/small_eod/institutions/tests/test_views.py
Add tests according to the issue
Update institutions factory so it can create tags
Add comment and tags to serializer
> Comments i Tags w instytucjach

- frontend-project/src/components/Login/index.tsx
- frontend-project/src/models/connect.d.ts
- frontend-project/src/models/login.ts
- frontend-project/src/pages/user/login/index.tsx
W końcu się za to wziąłem i chyba skończyłem- wszystko powinno już być w lepszym lub gorszym TypeScripcie.
Przy okazji odkryłem, że czasami mimo, że IDE (VSCode u mnie) nie podpowie samo z siebie dobrego interfejsu, to po zaaplikowaniu złego ts language server wyrzuci błąd sugerujący poprawny interfejs.
Zapraszam do znęcania się nad kodem
closes #419
> Migracja strony logowania do TypeScriptu

- backend-project/small_eod/cases/tests/test_serializers.py
- backend-project/small_eod/features/tests/test_serializers.py
- backend-project/small_eod/generic/tests/test_serializers.py
- backend-project/small_eod/letters/serializers.py
- backend-project/small_eod/letters/tests/test_serializers.py
- backend-project/small_eod/tags/serializers.py
- backend-project/small_eod/tags/tests/test_serializers.py
> Add id to TagSerializer and DocumentTypeSerializer

- backend-project/small_eod/letters/admin.py
Add management for document_type like in V1 (#397)
> Add management for document_type

- backend-project/small_eod/cases/models.py
- backend-project/small_eod/files/models.py
- backend-project/small_eod/institutions/models.py
- backend-project/small_eod/letters/admin.py
- backend-project/small_eod/letters/models.py
Add management for letters (#395) like in V1 (without action: download_selected_letters)
> New letter admin

- backend-project/requirements/base.txt
- backend-project/requirements/development.txt
- backend-project/small_eod/letters/admin.py
Add action **download selected letters** in LetterAdmin (#539)
> Add action download selected letters

- frontend-project/src/utils/Authorized.ts
- frontend-project/src/utils/authority.ts
Fix #332
Powinno odblokować  #551
Zastosowałem najprostsze rozwiązanie jakie przyszło mi do głowy- przeniosłem funkcję używającą circular dependency do pliku, który importowała
Jeżeli komuś to rozwiązanie się nie podoba, to spróbuję to inaczej rozwiązać ale proponuję i tak zaakceptować tego PR to szybciej <del>dostanę koszulkę [hacktoberfest](https://hacktoberfest.digitalocean.com/) (tak, jeszcze jest wrzesień)</del> będzie można zmergować PR z przeprowadzaniem testów na CI/CD
> Fix authority utils

- docs/scope-v2.md
W ramach wsparcia zarządzania projektem, a także zważywszy na temat realizacji elementów projektu z @mateuszmagulski poza CDP spisałem elementy etapu `v2`.
Zgodnie z ustaleniami dokonałem podziału na funkcjonalności niezbędne, a także funkcjonalności o czytelnym zakresie możliwe do realizacji w przyszłości. Wskazałem także w sposób wyraźny zakres zmian względem etapu `v1`.
Nie dokonywałem rozróżnienia na funkcjonalności, które obecnie są zaimplementowane w obszaru back-endu, a funkcjonalności, które dopiero takiej implementacji wymagają, chociaż dostrzegam, że w dużej części pracę są zaawansowane w tym obszarze.
> Add documentation of scope v2

- backend-project/small_eod/administrative_units/tests/test_serializers.py
- backend-project/small_eod/channels/tests/test_serializers.py
- backend-project/small_eod/collections/tests/test_serializers.py
- backend-project/small_eod/events/tests/test_serializers.py
- backend-project/small_eod/files/tests/test_serializers.py
- backend-project/small_eod/institutions/tests/test_serializers.py
- backend-project/small_eod/notes/tests/test_serializers.py
- backend-project/small_eod/users/tests/test_serializers.py
> adapt ResourceSerializerMixin for missing serializers

- .github/workflows/python.yaml
- backend-project/contrib/github/script.sh
Make CI output easier to read.
> Move python tests as seperate CI step

- frontend-project/src/models/login.ts
W #552 popsułem (nie wiem czemu nie zauważyłem), to teraz naprawiam
> Naprawienie błędu wynikającego ze złego importu

- frontend-project/README.md
- frontend-project/config/config.ts
- frontend-project/package.json
> Add support for public API server

- frontend-project/src/components/Authorized/Authorized.tsx
- frontend-project/src/components/Authorized/PromiseRender.tsx
- frontend-project/src/components/Authorized/Secured.tsx
- frontend-project/src/components/Login/LoginSubmit.tsx
- frontend-project/src/components/Login/LoginTab.tsx
- frontend-project/src/layouts/BasicLayout.tsx
- frontend-project/src/layouts/BlankLayout.tsx
- frontend-project/src/layouts/UserLayout.tsx
- frontend-project/src/pages/Authorized.tsx
- frontend-project/src/pages/cases/new/index.tsx
- frontend-project/src/pages/institutions/new/index.tsx
> Use FC instead of FunctionComponent

- .github/workflows/javascript.yaml
- frontend-project/tsconfig.json
> Add typecheck to CI/CD

- backend-project/small_eod/collections/tests/test_views.py
- backend-project/small_eod/collections/urls.py
- backend-project/small_eod/collections/views.py
1. Add `EventCollectionViewSetTestCase`
2. Update name of classes in `collections/views`:
- `CaseCollectionViewSet`
- `EventCollectionViewSet`
- `LetterCollectionViewSet`
- `NoteCollectionViewSet`
Part of: #495
> Add EventCollectionViewSetTestCase and update name of classes

- frontend-project/config/config.ts
> Fix tag list path

- backend-project/Dockerfile
- backend-project/config/settings/base.py
- backend-project/requirements/base.txt
- backend-project/small_eod/events/locale/pl/LC_MESSAGES/django.po
- backend-project/small_eod/events/templates/events/calendar_description.txt
- backend-project/small_eod/events/tests/test_views.py
- backend-project/small_eod/events/views.py
Step for #684
Missing:
- authentication (will be added in the coming PR)
> Add iCalendar export

- .github/workflows/javascript.yaml
Zmiana wersji z 12.x na 14.x
Obecny LTS to 14, nie widzę żadnego powodu, żeby używać 12
edit: widzę, że mi vscode plik od razu zlintowało, jak to problem, to mogę przywrócić tak jak było
> Change node version in JavaScript workflow

- README.md
We need that banner to start sponsored trier
> Add Vercel banner to readme.md

- .github/actions/h1-cli/.gitignore
- .github/actions/h1-cli/dist/index.js
- .github/actions/h1-cli/package-lock.json
- .github/actions/h1-cli/package.json
- .github/actions/h1-cli/src/start.js
Zmiana spowodowana przez https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/ . 
Zmiana naprawiana przez aktualizacje bibliotek: https://github.com/actions/toolkit/issues/630
> Fix deploy to H1 - bump @actions/ pkg - close #721

- frontend-project/package.json
- frontend-project/yarn.lock
Reverts watchdogpolska/small_eod#779
> Revert "fix(deps): update dependency umi-plugin-antd-icon-config to v2"
